language: node_js
os:
 - linux
 - osx
node_js:
 - "4"
 - "5"
 - "6"
 - "7"
 - "8"
 - "9"
 - lts/*
 - stable
sudo: false
install:
 - npm install
 - npm install coveralls
after_success:
 - node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls
